all : exploit1 exploit2 exploit3

exploit1 : exploit1.c
	gcc exploit1.c -o exploit1
exploit2 : exploit2.c
	gcc exploit2.c -o exploit2
exploit3 : exploit3.c
	gcc exploit3.c -o exploit3
.PHONY : clean
clean : 
	rm -rf exploit stack

